<a href="https://colab.research.google.com/github/reyllama/TTIO/blob/master/04_Rescaling_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import torch
from torch import nn, optim
from torch.autograd import Variable
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
path = "/content/drive/My Drive/corr1.csv"
df = pd.read_csv(path)
df = df.set_index(keys='stock_id')
df.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


000020    000040    000050  ...     99520     99660     99830
stock_id                                ...                              
000020    1.000000  0.221514 -0.037755  ...  0.101488  0.083284  0.116734
000040    0.221514  1.000000 -0.084175  ...  0.271006  0.171826  0.207319
000050   -0.037755 -0.084175  1.000000  ... -0.111201 -0.024860 -0.019401
000060   -0.021159  0.125700 -0.026910  ...  0.102192  0.063812  0.060242
000070    0.230919  0.048086  0.194396  ... -0.103425  0.048045 -0.010778

[5 rows x 2030 columns]

In [3]:
dtype = torch.FloatTensor
epochs = 50
emb_dim = 32
embeddings = Variable(torch.randn(emb_dim, len(df)).type(dtype), requires_grad=True)
lr = 0.005
optimizer = optim.SGD([embeddings], lr=lr)
mean = np.abs(df).mean().mean()
coef = 1/mean
loss_track = []

for epoch in range(epochs):
  loss = 0
  for i in range(len(df)):
    v1 = embeddings[:, i].view(emb_dim, -1)
    dist = torch.norm(v1 - embeddings, dim=0).view(len(df), 1)
    corrs = torch.from_numpy(np.abs(coef*np.array(df.iloc[:, i]))-1).view(1, len(df)).type(torch.FloatTensor)
    loss += torch.mm(corrs, dist)/2
  loss_track.append(loss.item())
  if (epoch+1) % 5 == 0:
    print("{0}th epoch in process".format(epoch+1))
    print('running loss: {}'.format(loss.item()))
    print()

  optimizer.zero_grad()
  loss.backward(retain_graph=True)
  optimizer.step()

  with torch.no_grad():
    for element in embeddings:
      element.clamp_(0,1)

embeddings[:, 1]  

5th epoch in process
running loss: -623784.9375

10th epoch in process
running loss: -780746.625

15th epoch in process
running loss: -708773.6875

20th epoch in process
running loss: -734358.3125

25th epoch in process
running loss: -737078.5625

30th epoch in process
running loss: -760899.0625

35th epoch in process
running loss: -824675.4375

40th epoch in process
running loss: -823476.0625

45th epoch in process
running loss: -860724.75

50th epoch in process
running loss: -827216.625



tensor([0.8718, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0937, 0.0000,
        1.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3677, 0.0000, 0.5608,
        0.0000, 0.0000, 0.0000, 1.0000, 1.0000, 0.0000, 0.1229, 1.0000, 0.0000,
        0.0000, 0.0000, 1.0000, 0.0882, 0.0000], grad_fn=<SelectBackward>)

In [4]:
embeddings

tensor([[0.8020, 0.8718, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 1.0000,  ..., 0.0000, 0.0000, 1.0000],
        [0.0000, 0.0000, 1.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.7875, 1.0000, 0.0000,  ..., 0.0000, 1.0000, 0.0000],
        [0.3970, 0.0882, 1.0000,  ..., 0.0000, 1.0000, 0.0000],
        [0.0000, 0.0000, 1.0000,  ..., 1.0000, 1.0000, 0.0000]],
       requires_grad=True)

## Rescaling Network

In [113]:
data = pd.read_csv("/content/drive/My Drive/stocks.csv")
data.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,1) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


stock_id  name        date  ...  lowest_price  closing_price  trading_volume
0   000020  동화약품  2016-01-04  ...          7920           8140          281440
1   000020  동화약품  2016-01-05  ...          8000           8190          243179
2   000020  동화약품  2016-01-06  ...          8110           8550          609906
3   000020  동화약품  2016-01-07  ...          8190           8380          704752
4   000020  동화약품  2016-01-08  ...          8130           8770          802330

[5 rows x 8 columns]

In [114]:
data['KLength'] = data['closing_price'] - data['opening_price']
data['KUpperLength'] = data['highest_price'] - data[['opening_price', 'closing_price']].max(axis=1)
data['temp'] = data['opening_price']-data['lowest_price']
data['KLowerLength'] = data[['closing_price', 'temp']].min(axis=1)
data['return'] = data['closing_price'].diff()
data = data.drop(columns=['temp'])
data['stock_id'] = data['stock_id'].astype(str)
## 첫날 빼줘야됨 (종목 바뀔때 섞여들어갔다)
data.head()

stock_id  name        date  ...  KUpperLength  KLowerLength  return
0   000020  동화약품  2016-01-04  ...            10           210     NaN
1   000020  동화약품  2016-01-05  ...            60            40    50.0
2   000020  동화약품  2016-01-06  ...            40            90   360.0
3   000020  동화약품  2016-01-07  ...           220           280  -170.0
4   000020  동화약품  2016-01-08  ...           130            80   390.0

[5 rows x 12 columns]

In [115]:
def year_parser(column):
  return int(column[0:4])

def month_parser(column):
  return int(column[5:7])

data['year'] = data['date'].apply(year_parser)
data['month'] = data['date'].apply(month_parser)

data = data[(data['year']==2016)&(data['month']<=6)]
data = data[data['stock_id'].isin(df.columns)]
# data = data.fillna(0)

KL = data.pivot(index='date', columns='stock_id', values='KLength')
R = data.pivot(index='date', columns='stock_id', values='return')

KL.shape

(121, 2030)

In [116]:
print(KL.shape, R.shape)

(121, 2030) (121, 2030)


In [117]:
KL = KL.iloc[:-1, ]
R = R.iloc[1:, ]

In [118]:
KL = KL.fillna(0)
R = R.fillna(0)

In [130]:
dtype = torch.FloatTensor
weights = Variable(torch.rand(1, 32).type(dtype), requires_grad=True)
lr = 0.05
optimizer = optim.SGD([weights], lr=lr)
epochs = 500
indic = np.array(KL)
returns = np.array(R)

for epoch in range(epochs):
  loss = 0

  rescale_fc = torch.exp(torch.mm(weights, embeddings)) / torch.sum(torch.exp(torch.mm(weights, embeddings)))
  opt_ind = torch.from_numpy(indic) * rescale_fc # element-wise
  # print('opt_ind: ', opt_ind)
  mean_ind = torch.mean(opt_ind, axis=0)
  # print('mean_ind: ', mean_ind)
  mean_ret = torch.mean(torch.from_numpy(returns), axis=0)
  # print('mean_ret: ', mean_ret)

  vx = opt_ind - mean_ind
  vy = torch.from_numpy(returns) - mean_ret
  # print('vx: ', vx)
  # print('vy: ', vy)
  loss = -torch.abs(torch.sum(vx * vy) / (torch.sqrt(torch.sum(vx ** 2)) * torch.sqrt(torch.sum(vy ** 2))))
  # print('loss: ', loss)

  if (epoch+1) % 50 == 0:
    print("{0}th epoch in process".format(epoch+1))
    print('running loss: {}'.format(loss.item()))
    print()

  optimizer.zero_grad()
  loss.backward(retain_graph=True)
  optimizer.step()

  with torch.no_grad():
    for weight in weights:
      weight.clamp_(0,1)

weights

50th epoch in process
running loss: -0.23575469466727395

100th epoch in process
running loss: -0.24138198184648657

150th epoch in process
running loss: -0.24291716706658018

200th epoch in process
running loss: -0.24359818579362438

250th epoch in process
running loss: -0.24400947203040615

300th epoch in process
running loss: -0.24428938605626754

350th epoch in process
running loss: -0.24449570638946883

400th epoch in process
running loss: -0.2446567266602514

450th epoch in process
running loss: -0.2447877880467779

500th epoch in process
running loss: -0.24489789899355893



tensor([[1.0787e-01, 4.5577e-01, 3.7170e-01, 1.8707e-04, 4.4074e-01, 8.1486e-01,
         2.2906e-01, 2.2651e-01, 1.6532e-01, 6.6833e-01, 3.3126e-01, 0.0000e+00,
         2.1989e-01, 4.7774e-01, 2.5917e-01, 4.1867e-01, 9.2924e-01, 5.3883e-01,
         6.7003e-01, 1.0000e+00, 1.7267e-01, 2.5216e-01, 7.6120e-01, 6.9733e-01,
         9.8284e-01, 1.6162e-01, 9.6101e-01, 9.1488e-01, 8.2262e-01, 6.1397e-01,
         1.5329e-01, 2.7696e-01]], requires_grad=True)